# Dockerfile
FROM ubuntu:trusty

RUN apt-get update -y && apt-get install software-properties-common -y
RUN apt-add-repository cloud-archive:liberty
RUN apt-get update -y && apt-get dist-upgrade -y --force-yes
RUN apt-get install python-requests git curl -y --force-yes

COPY ./fetch_and_install_deps.py /

