FROM        ubuntu:latest
RUN         DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y\
            docker.io \
            bash \
            git \
            make \
            nodejs \
            python \
            python-pip \
            sudo && rm -rf /var/lib/apt/lists/*
COPY        ./entrypoint.sh /entrypoint.sh
RUN         chmod +x /entrypoint.sh
ENTRYPOINT  ["/entrypoint.sh"]